version: '3'

services:
  gateway:
    image: gateway-image
    container_name: gateway
    expose:
      - 8080
    ports:
      - 8080:8080
  
  user-service:
    image: user-service-image
    container_name: user-service
    expose:
      - 8081
    ports:
      - 8081:8081
  
  posts-service:
    image: posts-service-image
    container_name: posts-service
    expose:
      - 8082
    ports:
      - 8082:8082